# Generated by Django 4.0.4 on 2022-05-25 18:41

import FileApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='upload/', validators=[FileApp.validators.validate_file_size], verbose_name='fichero'),
        ),
    ]
